name = "SCP: Data Redacted"
engine = "Unreal Engine 4"

languages = [ "C++", "Blueprint" ]

[[paragraphs]]
text = "SCP: Data Redacted was a project by me and a few other people based around the SCP Foundation and roleplaying as various roles inside of it. The project was massively over-scoped and never came to fruition, but me and others learned quite a bit of the development process while creating the parts of the game we managed to make."

[[paragraphs]]
text = "The idea was based around players roleplaying aspects of the Foundation, such as scientists, security and much more. We have a lot of indepth plans for SCP:DR but lacked the team for most of them."