name = "Source Editor"
engine = "Source 1"

languages = [ "C++", "C#", "CSS" ]
software = [ "Qt", "Mono" ]

[[paragraphs]]
text = "Source Editor was my attempt at a UE4 styled editor for Source 1, based loosely on the Source 2 tools aswell. I decided on Qt for the framework as it allowed CSS styling, something I am decently familar with. The project never got completed, but it also features a basic C# loading system using Mono. This system could print to the console aswell as do other Source method if they were implemented, I used SWIG to generate the bindings and Mono to load them into Source. While the project wasn't completed, it taught me a bit about how Qt works and gave me some more ideas about other tools in the future."

[[paragraphs]]
text = "How the editor was planned to have worked was to allow users to create their own tools using our codebase, as it was open source this was pretty easy to do. The project got halted early on due to some roadblocks I hit and, due to Source's lack of documentation for what I was using, I was unable to finish the project."

[[links]]
icon = "bi-github"
name = "Github Repository"
url = "https://github.com/AWildErin/SourceEditor-sdk"