name = "UDK Level Viewer"

languages = [ "C#" ]
software = [ "OpenTK" ]

description = "The content inside the screenshots (the models and such) are not mine and are owned by their respected owners."

[[paragraphs]]
text = "In September 2021 I decided to create a level viewer for UDK/UE3 based games. At the moment I don't have any full rendering down, however I have managed to create a level exporter through it."

[[paragraphs]]
text = "Currently the exporter doesn't support brushes which is why some of these levels feel empty, however that is slowly being worked on alongside Xenon support."

[[links]]
icon = "bi-github"
name = "Github Repository"
url = "https://github.com/AWildErin/udklevelviewer"

[[media]]
name = "Gears of War Judgement old town in the Gears of War 3 Editor"
url = "projects/udklevelviewer/gowj_oldtown_1.png"

[[media]]
name = "Gears of War Judgement old town in the Gears of War 3 Editor"
url = "projects/udklevelviewer/gowj_oldtown_2.png"

[[media]]
name = "Outlast labs in the UE3 Editor"
url = "projects/udklevelviewer/outlast_lab_1.png"

[[media]]
name = "Outlast labs in the UE3 Editor"
url = "projects/udklevelviewer/outlast_lab_2.png"

[[media]]
name = "Outlast labs in the UE3 Editor"
url = "projects/udklevelviewer/outlast_lab_3.png"

[[media]]
name = "Outlast labs in the UE3 Editor"
url = "projects/udklevelviewer/outlast_lab_4.png"
