name = "UDK Level Viewer"

languages = [ "C#" ]
software = [ "OpenTK" ]

description = "The content inside the screenshots (the models and such) are not mine and are owned by their respected owners."

[[paragraphs]]
text = "In September 2021 I decided to create a level viewer for UDK/UE3 based games. Through this project I gained a better understanding of OpenGL, rendering and how Unreal Engine 3 works."

[[paragraphs]]
text = "So far, the project has an exporter for UE3 levels to T3D supporting everything from lights to brushes. The level viewer can load UE3 models and materials fine, at the moment this has not been pushed to the main branch."

[[links]]
icon = "bi-github"
name = "Github Repository"
url = "https://github.com/AWildErin/udklevelviewer"

[[media]]
name = "Gears of War Judgement old town in the Gears of War 3 Editor"
url = "projects/udklevelviewer/gowj_oldtown_1.png"

[[media]]
name = "Gears of War Judgement old town in the Gears of War 3 Editor"
url = "projects/udklevelviewer/gowj_oldtown_2.png"

[[media]]
name = "Outlast labs in the UE3 Editor"
url = "projects/udklevelviewer/outlast_lab_1.png"

[[media]]
name = "Outlast labs in the UE3 Editor"
url = "projects/udklevelviewer/outlast_lab_2.png"

[[media]]
name = "Outlast labs in the UE3 Editor"
url = "projects/udklevelviewer/outlast_lab_3.png"

[[media]]
name = "Outlast labs in the UE3 Editor"
url = "projects/udklevelviewer/outlast_lab_4.png"
